services:
  web:
    container_name: nginx_web
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/winhome/website-project/versions/web-7.0/wwwroot:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/letsencrypt:ro
      - ./certs/www:/var/www/certbot:ro
